I2C master m33 example
dialog-semiconductor/BLE_SDK10_DA1470x_examples pull request #9
Opened 2022-08-23 08:09 UTC by blauret

2022-08-23 14:55 UTC, NiekIlmer requested changes
Couple of minor points

2022-08-23 14:55 UTC, NiekIlmer commented on interfaces/i2c_master_m33_demonstration_example/README.md
> +This example demonstrates using the I2C adapter layer employing the I2C1 block in master mode. The DA1470x family of devices comprises three separate I2C blocks instances. In this example, all of the
```suggestion
This example demonstrates using the I2C adapter layer employing the I2C1 block in master mode. The DA1470x family of devices comprises three separate I2C blocks instances. In this example, all of the I2C operations are executed in the SYSCPU context using the FreeRTOS preemptive scheduling. To make life easy, the I2C- and microBUS-compatible [`THERMO3` click board](https://www.mikroe.com/thermo-3-click) is utilized. The board comes with the `TMP102` temperature sensor which can trigger an external signal once the temperature exceeds or falls within a configurable temperature range. In this demonstration, the sensor is configured in comparator mode in which the alert pin is asserted once the temperature equals or exceeds the T<sub>high</sub> threshold and for as long as the temperature falls below the T<sub>low</sub> threshold. The alert signal is connected to the WKUP controller which is triggered once the signal is asserted. A single task, namely `termo3_task`,  is created and is responsible for configurating the sensor and reading the temperature for as long as the alert signal is asserted. The sample code comes with full drivers of the TMP102 temperature sensor which can be found in the [tmp102_drv/header/tmp102_reg.h](tmp102_drv/header/tmp102_reg.h) file.
```

2022-08-23 14:55 UTC, NiekIlmer commented on interfaces/i2c_master_m33_demonstration_example/README.md
> +  #define THERMO3_ALERT_PIN           ( HW_GPIO_PIN_24 )
I think it would be nicer to have a seperate definition like "#define MICRO_BUS 2", and based on that change the pins. I think that is something that should be done across all the examples

2022-08-23 14:55 UTC, NiekIlmer commented on interfaces/i2c_master_m33_demonstration_example/config/peripheral_setup.h
> +
```suggestion

#define MIKRO_BUS 2

```

2022-08-23 14:55 UTC, NiekIlmer commented on interfaces/i2c_master_m33_demonstration_example/config/peripheral_setup.h
> +
```suggestion

#if MIKRO_BUS == 1
```

2022-08-23 14:55 UTC, NiekIlmer commented on interfaces/i2c_master_m33_demonstration_example/config/peripheral_setup.h
> +#define THERMO3_ALERT_PORT          ( HW_GPIO_PORT_0 )
```suggestion
  #define THERMO3_ALERT_PORT          ( HW_GPIO_PORT_0 )
```

2022-08-23 14:55 UTC, NiekIlmer commented on interfaces/i2c_master_m33_demonstration_example/config/peripheral_setup.h
> +#define THERMO3_ALERT_PIN           ( HW_GPIO_PIN_24 )
```suggestion
  #define THERMO3_ALERT_PIN           ( HW_GPIO_PIN_23 )
#else
  #define THERMO3_ALERT_PORT          ( HW_GPIO_PORT_0 )
  #define THERMO3_ALERT_PIN           ( HW_GPIO_PIN_24 )
#endif
```

2022-08-24 13:14 UTC, blauret commented on interfaces/i2c_master_m33_demonstration_example/README.md
> +  #define THERMO3_ALERT_PIN           ( HW_GPIO_PIN_24 )
I propose we do that in another PR

2022-08-24 13:24 UTC, blauret commented on interfaces/i2c_master_m33_demonstration_example/config/peripheral_setup.h
> +
This has been addressed

2022-08-24 13:25 UTC, blauret commented on interfaces/i2c_master_m33_demonstration_example/config/peripheral_setup.h
> +
This  has been addressed

2022-08-26 09:35 UTC, blauret commented
@NiekIlmer, All comments should be resolved now.

2022-08-29 08:45 UTC, NiekIlmer approved these changes

2022-08-29 12:11 UTC, merged